### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by sirkitree** [lisa-lionheart/janus-server#10]
The VR Sites server uses pm2 to run the server process. On a new start it takes up about 32MB of RAM but after a few hours we're into the 100's and after 8 hours 475MB.

Going to try https://github.com/marcominetti/node-memwatch when I have a chance to see if I can pinpoint the problem.

**Comment by hazardu5** [comment]
It'd be interesting to see where the memory leak is coming from. I heard talk that someone was going to rewrite the network functionality in their version of the server code using socket.io for better performance. I suspect that the default socket implementation isn't handling the flood of user movement data that's flowing through it and is holding onto it in memory longer than it should...

**Comment by lisa-lionheart** [comment]
Has anyone got a way of reproducing this in a controlled manner. I've had some success tracking down a memory leak like this using https://github.com/node-inspector/node-inspector in the past

**Comment by sirkitree** [comment]
Here are the details of how we're running it on VR Sites, but you'll need a way to simulate traffic (though probably not a ton) in order to reproduce:

* node v0.13.0-pre
* janus-server installed in `/root/janus-server`
* pm2 v0.12.8
* running pm2 with root to start the process in 'fork' mode 

Some notes:
* pm2 cluster mode creates two processes and people connected to one don't see people in the other, hence using fork mode
* there was a resource leak error in pm2 recently fixed, so it's possible this is a problem with pm2 still
* others are running without pm2 and are not reporting memory leaks

I'm going to try running it without pm2 today and observe the memory usage.

**Comment by sirkitree** [comment]
Seems to still be leaking. After just half an hour it's memory usage has gone from 1.7% to 3.4%

**Comment by sirkitree** [comment]
So I have this running locally and can reproduce it as well.

I've installed janus-server on my mac as well as pm2. I then run the client on my mac (hallelujah!) and cd to `/Applications/janusvr.app/Contents/MacOS` and run `./janusvr -server localhost -port 5566`

Client reports I'm connected to my localhost.

I then run `p2m monit` and watch my memory usage climb as I move around the lobby in the client.

node-inspector coming up next.

**Comment by sirkitree** [comment]
I'm getting results with node-inspector, but I'm not entirely sure what they mean or where to go from here. Here's what I've found:

Taking a heap snapshot upon my initial client connection doesn't look too bad. But then I just take a spin around the lobby in the client and take another heap snapshot and the first thing I notice is a huge jump in the number of Objects.

**Initial connection heap snapshot**
![node inspector 2015-03-22 10-52-11](https://cloud.githubusercontent.com/assets/28543/6770295/8241f450-d081-11e4-966a-548f8ade89d6.png)

**After a short stroll in the lobby**
![node inspector 2015-03-22 10-52-39](https://cloud.githubusercontent.com/assets/28543/6770300/968a766c-d081-11e4-8bdf-d6dee7d4f073.png)

The `Objects Count` is fairly consistent between the two, around `4,800`, but in opening the `Object` in the second heap snapshot, I'm seeing `@543` at the top with a huge `Retained Size`.
![node inspector 2015-03-22 11-00-51](https://cloud.githubusercontent.com/assets/28543/6770336/bc34ae04-d082-11e4-9f70-a156ca08e5c7.png)

I'm not sure how else to read this other than the `global` scope is out of control.

Thoughts? I've very little experience with heap snapshots.

**Comment by hazardu5** [comment]
What version of node is the vrsites server running? If it's an unstable version it could be contributing to the problem. From a quick glance, I can't see anything in the code that could be contributing to the issue apart from some possible stuff in Logging.js as it is declaring stuff in the global scope. Could be worth disabling logging to see if that helps.

**Comment by sirkitree** [comment]
Currently running v0.12.0. It was running v0.13.0-pre but I reasoned the same as you and switched to a stable version. Memory consumption there is still increasing. 

Looks like there is no way to disable logging with a param, have to modify the code... /me logs an issue

**Comment by sirkitree** [comment]
I removed all of the log calls but that doesn't seem to help much.

Of note is that my local never seems to climb much past ~40 - 50MB, so it seems like this is multiplied per user connection as it jumps some during another connection, however I think my mac's memory management may also be coming into play because around 50MB, it seems to jump back down to 32MB.

I'm not sure what would cause that, but I wish I could replicate that on the linux server...

**Comment by hazardu5** [comment]
Ok so it sounds like it's garbage collecting on your dev machine which is good. I wonder if it'd be worth writing some fake headless clients using node and spinning up multiple instances of them to see if you can replicate what's happening with the Linux server? You could also try provisioning a replica of the Linux server with the same packages/node version inside a VM to see if that works. Another thing to try would be to run npm install on the Linux server as some of the dependencies for the node server may be out of date or buggy which could be contributing to the memory leak.

**Comment by sirkitree** [comment]
Seems like there was a pretty big issue a while back with express and memory leaks. I'm going to try ripping that portion of the code out and see if it helps. It's not really doing anything useful anyway other than dumping a file that can get way too large onto a screen anyway.

**Comment by hazardu5** [comment]
I've been thinking more about possible causes and I'm wondering if we could be having memory leak issues because we're piping huge amounts of data through raw sockets in Node without any streaming and buffering?

**Comment by sirkitree** [comment]
Do you think something like socket.io would work better?

**Comment by lisa-lionheart** [comment]
I doubt it. Socket.IO is for doing web-sockets and handling fallbacks for browsers that dont support websockets. I verry much doubt its going to be more efficient than a vanilla TCP/IP socket.

**Comment by lisa-lionheart** [comment]
There are a couple of things I can think of that could be cause issues. 

- Firstly the byline modules, I'm not sure what the hell its doing it could be doing something nasty.
- Does Janus actually ever unsubscribe from rooms? If it creating a subscription and not unsubscribing when a room get unloaded it could be adding a lot of overhead.

**Comment by JamesMcCrae** [comment]
Janus does unsubscribe.  However, if the process is killed or Janus crashes, then no unsubscribe is sent.  Could the memory issue have to do with keeping a connection open/memory allocated for a crashed client?

Also, is this actually a "leak"?  1.7 to 3.4% seems very reasonable.  Maybe only the needed working memory is allocated based on the number of simultaneously connected clients, but then it is not reclaimed later because there isn't a need to immediately?  This is just speculation.

**Comment by lisa-lionheart** [comment]
Hmmmm something to consider how is it handling hangups

**Comment by sirkitree** [comment]
The process is still consistently gobbling up RAM. I restarted it yesterday and just checked and it's consuming 1.190 GB currently. So I'm not sure.

**Comment by sirkitree** [comment]
THis hasn't been a big problem of late.
