### ISSUE TITLE
Subscribe calls

### ISSUE THREAD

**Issue by oculushut** [lisa-lionheart/janus-server#13]
Hi, just been messing around with my install and trying to understand how things work by chucking in loads of debug.

I'm using the 40.0 version of JanusVR client and noticed that there is a constant stream of subscribe calls to my server when I connect up a Janus VR client (i.e. calling Session.prototype.subscribe):

e.g.

```
info 19:12:17 src/Session.js:191 wongo just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:155 wongo just moved to [object Object]
info 19:12:17 src/Session.js:191 oculushut just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:191 wongo just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:191 oculushut just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:191 wongo just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:191 wongo just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:191 oculushut just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:191 wongo just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:191 oculushut just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:191 wongo just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:191 oculushut just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:155 oculushut just moved to [object Object]
info 19:12:17 src/Session.js:191 wongo just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:191 oculushut just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:191 wongo just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:155 wongo just moved to [object Object]
info 19:12:17 src/Session.js:191 oculushut just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:191 wongo just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:191 oculushut just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:191 wongo just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:191 oculushut just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:191 wongo just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:191 oculushut just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:191 wongo just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:191 oculushut just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:191 wongo just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:191 oculushut just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:155 oculushut just moved to [object Object]
info 19:12:17 src/Session.js:191 wongo just subscribed to e562b2e1339fc08d635d28481121857c
info 19:12:17 src/Session.js:191 oculushut just subscribed to e562b2e1339fc08d635d28481121857c
```

Is this what is suppose to happen by design?  E.g. keep-alive etc or are there not suppose to be that many calls?

The above log is just when I have 2 x JanusVR clients in the same room.  Only one of them is walking at any moment in time (since I only have 1 x kb and mouse :P).

**Comment by hazardu5** [comment]
Sounds like a client bug to me... I wonder if it was introduced after support for room specific servers was added a few versions ago?

**Comment by oculushut** [comment]
Do you know if James watches this project?  Or better post on Reddit?

**Comment by hazardu5** [comment]
This should probably go on Reddit otherwise he might miss it :-)

**Comment by oculushut** [comment]
Cool.  OK, [just posted here](http://www.reddit.com/r/janusVR/comments/30kvbb/release_40_directtorift_support_updated_to_sdk/)

Also, noted that I haven't upgraded to recommended Oculus runtime either.  Will have to get on that...

**Comment by JamesMcCrae** [comment]
Whoa!  OK I will look into that one NOW :)

**Comment by JamesMcCrae** [comment]
This bug will be fixed in 40.2.  Janus was spamming subscribe requests for the current room!

**Comment by oculushut** [comment]
That was quick!  
I'll switch over to 40.2 in my next tests :)

**Comment by sirkitree** [comment]
wonder if this will reduce that memory leak.

**Comment by sirkitree** [comment]
I think this has helped the memory leak issue #10. I'm still seeing an increase in memory, but where as we were consuming on average 800MB per day, it's not something like 100MB per day. So probably still some work to do in #10 but this has helped it seems.

Thank you @oculushut and @JamesMcCrae!

**Comment by oculushut** [comment]
Hey sirkitree - I've been trying to run a test to see if there was evidence of a leak in the subscribe call code.  

![graph shows the results](http://i.imgur.com/nyN352Q.jpg).  

This does not really replicate what a user with the subscribe bug would do, but it does try to focus in on the subscribe and logon calls.  The test included 133 998 iterations over a period of around 14/15 hours.  So should include approximately:

* Over 1 million calls to subscribe method
* Over 100K socket connects/disconnects
* Over 100K logon calls

I think the virtual memory measurement will include mem usage from other apps, but it's probably an OK estimate for detecting a memory leak since I did't really do much else on the instance during the test period (the test harness was also on a different box).

I'll try and run an instance with just move calls next and see what happens on that.  I wanna check out 40.2 and the new [stats release](http://www.reddit.com/r/janusVR/comments/31lvgi/modification_to_multiplayer_server_allows_access/) from @source83 beforehand so not sure when I will have results for you!

Btw -> If somebody is using a version of JanusVR which is older than 40.2 then would your server still service them?

(Never thought I would say this, but testing this thing is actually quite fun :P)

I'll close off this issue as soon as I have done a retest with a version of JanusVR client which is 40.2 or newer.

**Comment by oculushut** [comment]
Oh -> do note that I always subscribe to the same room though so if there are issues in other program flows (such as when you enter lots of different rooms) then this would not show up... Another potential test case i could add to the list for later.

**Comment by sirkitree** [comment]
> If somebody is using a version of JanusVR which is older than 40.2 then would your server still service them?

Yes, we don't discriminate against versions in the server code :wink:

**Comment by oculushut** [comment]
OK, just retested.  Saw the problem with the old version (40.0) and I don't see it in 40.3.  All I see is the movement info being passed up to the server now.  This kind of thing:

```
info 01:14:11 src/Session.js:157 ProudMinna333 just moved to [object Object]
info 01:14:11 src/Session.js:157 ProudMinna333 just moved to [object Object]
info 01:14:11 src/Session.js:157 ProudMinna333 just moved to [object Object]
info 01:14:11 src/Session.js:157 ProudMinna333 just moved to [object Object]
info 01:14:11 src/Session.js:157 ProudMinna333 just moved to [object Object]
info 01:14:12 src/Session.js:157 ProudMinna333 just moved to [object Object]
info 01:14:12 src/Session.js:157 ProudMinna333 just moved to [object Object]
```

**Comment by oculushut** [comment]
Closinging this issue!

**Comment by lisa-lionheart** [comment]
Just caught up, excellent work everyone
